#!/usr/bin/env python

import sys
import os.path
import tempfile
import signal
import subprocess


src = os.path.join(os.path.dirname(__file__), 'src')


hsl = src + '/Main.hs'


def main():
    binary = os.path.join(tempfile.mkdtemp(), 'Main')
    mainhs = binary + '.hs'

    f = sys.argv[1:][-1]
    inits = "\n\n".join(sys.argv[1:-1])

    fh = open(mainhs, 'w')
    fh.write(open(hsl).read() % (inits, f))
    fh.close()

    ghc = ['ghc', '-O2', '-i' + src, mainhs]

    if not subprocess.Popen(ghc, stdout=subprocess.PIPE).wait():
        p = subprocess.Popen(binary)
        try:
            p.wait()
        except (KeyboardInterrupt, IOError):
            p.send_signal(signal.SIGTERM)


main()
