name:           haskell-awk
version:        1.1.1
github:         gelisam/hawk
author:         Mario Pastorelli <pastorelli.mario@gmail.com>,  Samuel Gélineau <gelisam@gmail.com>
maintainer:     Mario Pastorelli <pastorelli.mario@gmail.com>,  Samuel Gélineau <gelisam@gmail.com>
synopsis:       Transform text from the command-line using Haskell expressions.
description:    Hawk is a command line utility to process streams of text
                using Haskell code. It is intended to be used in a UNIX
                pipeline. It offers a configuration system to personalize
                imported modules and a way to represent values on the console.
category:       Console
license:        Apache-2.0
license-file:   LICENSE
extra-source-files:
- README.md
- CHANGELOG.md

ghc-options: -Wall
dependencies:
  - base >= 4.13.0.0 && < 5
  - bytestring >= 0.10.10.1
  - containers >= 0.6.2.1
  - ghc >= 8.8.4
  - list-t >= 1.0.4
  - stringsearch >= 0.3.6.6

# Windows is not currently supported, see issue #248
when:
  - condition: os(windows)
    dependencies:
      - base < 0

custom-setup:
  dependencies:
    - base >= 4.13.0.0 && < 5
    - Cabal >= 3.0.1.0
    - cabal-doctest >= 1.0.8

library:
  source-dirs: runtime

executables:
  hawk:
    main:        Main.hs
    dependencies:
      - directory >= 1.3.6.0
      - exceptions >= 0.10.4
      - extra >= 1.7.9
      - filelock >= 0.1.1.5
      - filepath >= 1.4.2.1
      - haskell-awk
      - haskell-src-exts >= 1.23.1
      - hint >= 0.9.0.3
      - mtl >= 2.2.2
      - process >= 1.6.9.0
      - template-haskell >= 2.15.0.0
      - time >= 1.9.3
      - transformers >= 0.5.6.2
    source-dirs: src

tests:
  reference:
    source-dirs:
      - src
      - tests
    main:                 RunTests.hs
    dependencies:
      - aeson >= 1.4.7.1
      - attoparsec >= 0.13.2.4
      - directory >= 1.3.6.0
      - doctest >= 0.16.3
      - easy-file >= 0.2.2
      - exceptions >= 0.10.4
      - extra >= 1.7.9
      - filelock >= 0.1.1.5
      - filepath >= 1.4.2.1
      - haskell-awk
      - haskell-src-exts >= 1.23.1
      - hint >= 0.9.0.3
      - hspec >= 2.7.6
      - HUnit >= 1.6.1.0
      - mtl >= 2.2.2
      - process >= 1.6.9.0
      - template-haskell >= 2.15.0.0
      - temporary >= 1.3
      - test-framework >= 0.8.2.0
      - test-framework-hunit >= 0.3.0.2
      - time >= 1.9.3
      - transformers >= 0.5.6.2
